import React from 'react';
import Head from 'next/head';
import Layout from '@/components/Layout';
import List from '@/components/List';
import SpotifyService from '@/infrastructure/service/SpotifyService';

export async function getStaticProps() {
  console.log('getStaticProps');
  const token = await SpotifyService.getAccessToken();
  return { props: { token } };
}

type PropsType = {
  token: string;
};

export default function Home({ token }: PropsType) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {token}
        <List />
      </Layout>
    </>
  );
}
